version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: snippetbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 650464
      ports: 5432:5432
  app:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "./cmd/web"]
    volumes:
      - .:/go/src/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    links:
      - db